title: tools-hackathon-2019-typescript-introduction
tagline: Typescript Introduction for Newbies in the context of the 2019 Tools Hackathon
description: Typescript Introduction for Newbies in the context of the 2019 Tools Hackathon
template:
  repo: tools-hackathon-2019-typescript-introduction-template
  name: tools-hackathon-2019-typescript-introduction-exercise
  description: >-
    Repository for exploring the Learning Lab course
    "tools-hackathon-2019-typescript-introduction"
before:
  - type: createIssue
    title: >-
      Welcome to the exercise regarding
      "tools-hackathon-2019-typescript-introduction"
    body: Enjoy the Show
    action_id: akshay1
steps:
  - title: Install Git
    description: 'You can download Git from https://git-scm.com/downloads'
    event: issues.closed
    link: '{{ repoUrl }}'
    actions:
      - type: createIssue
        title: Install Git  
        body: Install Git from https://git-scm.com/downloads
